# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/wordslab-llms-lib',
                'doc_host': 'https://wordslab-org.github.io',
                'git_url': 'https://github.com/wordslab-org/wordslab-llms-lib',
                'lib_path': 'wordslab_llms'},
  'syms': {'wordslab_llms.models': {'wordslab_llms.models.test': ('models.html#test', 'wordslab_llms/models.py')}}}
